/**
 * Centralized mapping of available visa & residency services by country of residence.
 * Based on AAA Business Consultancy LLC workflow requirements.
 */

export const ALL_VISA_SERVICES = [
  { id: 'dnv', name: 'Spain Digital Nomad Visa (DNV)', category: 'residency' },
  { id: 'nlv', name: 'Spain Non-Lucrative Visa (NLV)', category: 'residency' },
  { id: 'study', name: 'Spain Study Visa', category: 'study' },
  { id: 'business', name: 'Spain Self-Employed / Business Visa', category: 'business' },
  { id: 'tourist', name: 'Spain Tourist Visa (Schengen)', category: 'tourist' },
  { id: 'golden', name: 'Spain Golden Visa / Property', category: 'investment' }
];

export const ALL_COUNTRIES = [
  "United Arab Emirates",
  "Saudi Arabia",
  "Bahrain",
  "Egypt",
  "India",
  "Kuwait",
  "Oman",
  "Pakistan",
  "Philippines",
  "Qatar",
  "Spain",
  "United Kingdom",
  "United States",
  "Canada",
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Cape Verde",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Poland",
  "Portugal",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Other"
];

export const COUNTRY_SERVICES_MAPPING = {
  'Bahrain': [
    { id: 'tourist', name: 'Spain Tourist Visa (Schengen)' },
    { id: 'study', name: 'Spain Study Visa' }
  ],
  'Egypt': [
    { id: 'dnv', name: 'Spain Digital Nomad Visa (DNV)' },
    { id: 'nlv', name: 'Spain Non-Lucrative Visa (NLV)' },
    { id: 'study', name: 'Spain Study Visa' },
    { id: 'tourist', name: 'Spain Tourist Visa (Schengen)' }
  ],
  'India': [
    { id: 'dnv', name: 'Spain Digital Nomad Visa (DNV)' },
    { id: 'nlv', name: 'Spain Non-Lucrative Visa (NLV)' },
    { id: 'study', name: 'Spain Study Visa' },
    { id: 'tourist', name: 'Spain Tourist Visa (Schengen)' }
  ],
  'Kuwait': [
    { id: 'tourist', name: 'Spain Tourist Visa (Schengen)' },
    { id: 'study', name: 'Spain Study Visa' }
  ],
  'Oman': [
    { id: 'dnv', name: 'Spain Digital Nomad Visa (DNV)' },
    { id: 'nlv', name: 'Spain Non-Lucrative Visa (NLV)' },
    { id: 'study', name: 'Spain Study Visa' },
    { id: 'tourist', name: 'Spain Tourist Visa (Schengen)' }
  ],
  'Pakistan': [
    { id: 'tourist', name: 'Spain Tourist Visa (Schengen)' },
    { id: 'study', name: 'Spain Study Visa' }
  ],
  'Philippines': [
    { id: 'dnv', name: 'Spain Digital Nomad Visa (DNV)' },
    { id: 'nlv', name: 'Spain Non-Lucrative Visa (NLV)' },
    { id: 'study', name: 'Spain Study Visa' },
    { id: 'tourist', name: 'Spain Tourist Visa (Schengen)' }
  ],
  'Qatar': [
    { id: 'study', name: 'Spain Study Visa' },
    { id: 'nlv', name: 'Spain Non-Lucrative Visa (NLV)' },
    { id: 'tourist', name: 'Spain Tourist Visa (Schengen)' }
  ],
  'Saudi Arabia': [
    { id: 'dnv', name: 'Spain Digital Nomad Visa (DNV)' },
    { id: 'nlv', name: 'Spain Non-Lucrative Visa (NLV)' },
    { id: 'study', name: 'Spain Study Visa' },
    { id: 'tourist', name: 'Spain Tourist Visa (Schengen)' }
  ],
  'United Arab Emirates': [
    { id: 'study', name: 'Spain Study Visa' },
    { id: 'dnv', name: 'Spain Digital Nomad Visa (DNV)' },
    { id: 'nlv', name: 'Spain Non-Lucrative Visa (NLV)' },
    { id: 'business', name: 'Spain Self-Employed / Business Visa' },
    { id: 'tourist', name: 'Spain Tourist Visa (Schengen)' }
  ],
  'UAE': [
    { id: 'study', name: 'Spain Study Visa' },
    { id: 'dnv', name: 'Spain Digital Nomad Visa (DNV)' },
    { id: 'nlv', name: 'Spain Non-Lucrative Visa (NLV)' },
    { id: 'business', name: 'Spain Self-Employed / Business Visa' },
    { id: 'tourist', name: 'Spain Tourist Visa (Schengen)' }
  ]
};

/**
 * Returns available visa services for a given country of residence.
 * Falls back to ALL_VISA_SERVICES if country is missing or not explicitly mapped.
 */
export function getServicesForCountry(countryName) {
  if (!countryName) return ALL_VISA_SERVICES;
  
  const normalizedCountry = Object.keys(COUNTRY_SERVICES_MAPPING).find(
    c => c.toLowerCase() === countryName.trim().toLowerCase()
  );

  return normalizedCountry ? COUNTRY_SERVICES_MAPPING[normalizedCountry] : ALL_VISA_SERVICES;
}
